/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Graphique;

import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import projet_trinome.Jeu;

/**
 *
 * @author louie
 */
public class Fenetre_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Fenetre_Menu
     */
    private Fenetre_Jeu fJeu;
    public projet_trinome.Jeu jeu;
    private String pseudoJ1;
    private String pseudoJ2;
    private int spe;
    
    public Fenetre_Menu(){
            initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgPieceSpe = new javax.swing.ButtonGroup();
        lPrompt = new javax.swing.JLabel();
        lJoueur1 = new javax.swing.JLabel();
        lJoueur2 = new javax.swing.JLabel();
        tfJoueur1 = new javax.swing.JTextField();
        tfJoueur2 = new javax.swing.JTextField();
        bValiderJ1 = new javax.swing.JButton();
        bValiderJ2 = new javax.swing.JButton();
        bNvPartie = new javax.swing.JButton();
        bQuitter = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        lSpeciales = new javax.swing.JLabel();
        rbPieceSpeActive = new javax.swing.JRadioButton();
        rbPieceSpeInactive = new javax.swing.JRadioButton();
        bChPartie = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Trinôme ");

        lPrompt.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        lPrompt.setForeground(new java.awt.Color(255, 51, 51));
        lPrompt.setText("Veuillez entrer les noms des joueurs");

        lJoueur1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lJoueur1.setText("Joueur 1");

        lJoueur2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        lJoueur2.setText("Joueur 2");

        tfJoueur1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfJoueur1.setToolTipText("");
        tfJoueur1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJoueur1ActionPerformed(evt);
            }
        });

        tfJoueur2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        tfJoueur2.setToolTipText("");
        tfJoueur2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfJoueur2ActionPerformed(evt);
            }
        });

        bValiderJ1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bValiderJ1.setText("Valider");
        bValiderJ1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderJ1ActionPerformed(evt);
            }
        });

        bValiderJ2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        bValiderJ2.setText("Valider");
        bValiderJ2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bValiderJ2ActionPerformed(evt);
            }
        });

        bNvPartie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bNvPartie.setText("Nouvelle Partie");
        bNvPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bNvPartieActionPerformed(evt);
            }
        });

        bQuitter.setText("Quitter");
        bQuitter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bQuitterActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lSpeciales.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lSpeciales.setText("Pièces spéciales");

        bgPieceSpe.add(rbPieceSpeActive);
        rbPieceSpeActive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPieceSpeActive.setText("Activées");
        rbPieceSpeActive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPieceSpeActiveActionPerformed(evt);
            }
        });

        bgPieceSpe.add(rbPieceSpeInactive);
        rbPieceSpeInactive.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        rbPieceSpeInactive.setText("Désactivées");
        rbPieceSpeInactive.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbPieceSpeInactiveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lSpeciales)
                    .addComponent(rbPieceSpeActive)
                    .addComponent(rbPieceSpeInactive))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lSpeciales)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(rbPieceSpeActive)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(rbPieceSpeInactive)
                .addContainerGap())
        );

        bChPartie.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        bChPartie.setText("Reprendre Partie");
        bChPartie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bChPartieActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(bQuitter, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(bChPartie))
                    .addComponent(bNvPartie, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(89, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lPrompt)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lJoueur1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfJoueur1, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bValiderJ1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lJoueur2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfJoueur2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(bValiderJ2)))
                .addGap(64, 64, 64))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lPrompt)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lJoueur1)
                    .addComponent(tfJoueur1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bValiderJ1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lJoueur2)
                    .addComponent(tfJoueur2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bValiderJ2))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(8, 8, 8)
                        .addComponent(bNvPartie)
                        .addGap(18, 18, 18)
                        .addComponent(bChPartie)
                        .addGap(18, 18, 18)
                        .addComponent(bQuitter))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tfJoueur1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJoueur1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfJoueur1ActionPerformed

    private void tfJoueur2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfJoueur2ActionPerformed
        
    }//GEN-LAST:event_tfJoueur2ActionPerformed

    private void rbPieceSpeActiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPieceSpeActiveActionPerformed
        if (rbPieceSpeActive.isSelected()){
            spe = 0;
        }
    }//GEN-LAST:event_rbPieceSpeActiveActionPerformed

    private void rbPieceSpeInactiveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbPieceSpeInactiveActionPerformed
        if (rbPieceSpeInactive.isSelected()){
            spe = 1;
        }
    }//GEN-LAST:event_rbPieceSpeInactiveActionPerformed

    private void bQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bQuitterActionPerformed
        System.exit(0);
    }//GEN-LAST:event_bQuitterActionPerformed

    private void bNvPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bNvPartieActionPerformed
        //Jeu jeu;
         try {
            testErreurs();
            this.setVisible(false);
            jeu = new Jeu(1, pseudoJ1, pseudoJ2, spe);
            fJeu = new Fenetre_Jeu (this, false, jeu);
            fJeu.SetPseudo();
            fJeu.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Fenetre_Menu.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ErreurMenu e){
            JOptionPane.showMessageDialog(this, e.getMessage()); //Affiche une fenêtre de dialogue si l'utilisateur oublie de selectionner un type de partie
        } catch(ErreurPlayerName e){
            JOptionPane.showMessageDialog(this, e.getMessage()); //Affiche une fenêtre de dialogue si l'utilisateur oublie d'entrer un ou 2 pseudos
        }
    }//GEN-LAST:event_bNvPartieActionPerformed

    private void testErreurs(){
        if (!rbPieceSpeInactive.isSelected() && !rbPieceSpeActive.isSelected()){
            throw new ErreurMenu("Veuillez selectionner un type de partie");
        }
        if (pseudoJ1 == null || pseudoJ2 == null){
            throw new ErreurPlayerName("Veuillez entrer et valider un nom pour les deux joueurs");
        }
    }
    
    private void bChPartieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bChPartieActionPerformed
        try {
            jeu = new Jeu(2, pseudoJ1, pseudoJ2, 0);
            fJeu = new Fenetre_Jeu (this, false, jeu);
            fJeu.SetPseudo();
            fJeu.setVisible(true);
        } catch (IOException ex) {
            Logger.getLogger(Fenetre_Menu.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_bChPartieActionPerformed

    private void bValiderJ2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderJ2ActionPerformed
        if (!tfJoueur2.getText().equals("")){
            pseudoJ2 = tfJoueur2.getText();
            JOptionPane.showMessageDialog(this, "Le nom du joueur 2 est : " + pseudoJ2);
        }else{
            JOptionPane.showMessageDialog(this, "Veuillez entrer le nom du joueur 2");
        }        
    }//GEN-LAST:event_bValiderJ2ActionPerformed

    private void bValiderJ1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bValiderJ1ActionPerformed
        if (!tfJoueur1.getText().equals("")){
            pseudoJ1 = tfJoueur1.getText();
            JOptionPane.showMessageDialog(this, "Le nom du joueur 1 est : " + pseudoJ1);
        }else{
            JOptionPane.showMessageDialog(this, "Veuillez entrer le nom du joueur 1");
        }
    }//GEN-LAST:event_bValiderJ1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fenetre_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fenetre_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bChPartie;
    private javax.swing.JButton bNvPartie;
    private javax.swing.JButton bQuitter;
    private javax.swing.JButton bValiderJ1;
    private javax.swing.JButton bValiderJ2;
    private javax.swing.ButtonGroup bgPieceSpe;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lJoueur1;
    private javax.swing.JLabel lJoueur2;
    private javax.swing.JLabel lPrompt;
    private javax.swing.JLabel lSpeciales;
    private javax.swing.JRadioButton rbPieceSpeActive;
    private javax.swing.JRadioButton rbPieceSpeInactive;
    private javax.swing.JTextField tfJoueur1;
    private javax.swing.JTextField tfJoueur2;
    // End of variables declaration//GEN-END:variables
}
